unbind r
bind r source-file ~/.tmux.conf
# Change leader key to Ctrl+s
set -g prefix C-s

# Mouse support
set -g mouse on

#LDUR
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Tokyo night theme config
set -g @powerkit_plugins "datetime,battery,cpu,memory,hostname"
set -g @powerkit_plugin_datetime_format "%a, %d/%m/%y %I:%M %p"
set -g @powerkit_theme "onedark"
set -g @powerkit_theme_variant "dark"
set -g @powerkit_edge_separator_style "normal"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

